# Generated by Django 5.2 on 2025-04-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='registroSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('año', models.IntegerField(default=2025)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conductores.conductor')),
            ],
        ),
    ]
