# Generated by Django 5.2 on 2025-04-21 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['nombre'], 'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='registrosemanal',
            options={'ordering': ['-año', '-semana', 'conductor'], 'verbose_name': 'Registro Semanal', 'verbose_name_plural': 'Registros Semanales'},
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='registrosemanal',
            name='año',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000, 'El año debe ser mayor a 2000')], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='registrosemanal',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conductores.conductor', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='registrosemanal',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='registrosemanal',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='registrosemanal',
            name='semana',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'La semana debe ser mayor a 0'), django.core.validators.MaxValueValidator(53, 'La semana no puede ser mayor a 53')], verbose_name='Semana'),
        ),
        migrations.AlterUniqueTogether(
            name='registrosemanal',
            unique_together={('conductor', 'semana', 'año')},
        ),
    ]
